[package]
name = "lang-interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
bytes = "1.3.0"
thiserror = "1.0.63"